### ISSUE TITLE
Beats input stops processing messages after creating extractor

### ISSUE THREAD

**Issue by mihall-primus** [sivasamyk/graylog-beats-plugin#4]
Hi sivasamyk,

I'm testing Filebeat 1.2.1 on one of our preprod web servers, sending the Apache access log to a Graylog 1.3.3 virtual appliance via the Beats plugin 1.0.0.  This works fine, as long as I don't create any extractors on the Beats input.

The extractor I'm trying to create is very simple, just using the default %{COMMONAPACHELOG} grok pattern.  When I test the extractor against an already received message, it successfully parses it.  Once I save it, though, the input stops processing messages.

My syslog inputs work fine, but we can't configure Apache to log to syslog (the application vendor won't let us touch the Apache config file).

Thanks,

Michael

**Comment by sivasamyk** [comment]
Hi Michael,

Are there any exceptions present in graylog server log files? Please paste the contents of graylog server log files? ( Make sure you hide sensitive info)

**Comment by mihall-primus** [comment]
Hi Savasamy,

Ah ha!

2016-04-27_15:21:09.13131 [344]: index [graylog_73], type [message], id [aa4ba352-0c8b-11e6-afd3-005056a47198], message [MapperParsingException[failed to parse [timestamp]]; nested: MapperParsingException[failed to parse date field [27/Apr/2016:11:21:05 -0400], tried both date format [yyyy-MM-dd HH:mm:ss.SSS], and timestamp number with locale []]; nested: IllegalArgumentException[Invalid format: "27/Apr/2016:11:21:05 -0400" is malformed at "/Apr/2016:11:21:05 -0400"]; ]

I changed my extractor to just %{IP}, instead of %{COMMONAPACHELOG}, and it works fine.  So it looks like the problem is with the Grok pattern.  The weird part is, when I test the pattern on the Extractor Configuration page, it successfully parses the timestamp.  But then when it's actually running the extractor, it fails.

Michael

On Tue, 2016-04-26 at 17:38 -0700, Sivasamy Kaliappan wrote:
Hi Michael,

Are there any exceptions present in graylog server log files?

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHubhttps://github.com/sivasamyk/graylog-beats-plugin/issues/4#issuecomment-214929967

---

 This electronic message contains information from Primus Management ULC ("PRIMUS") , which may be legally privileged and confidential. The information is intended to be for the use of the individual(s) or entity named above. If you are not the intended recipient, be aware that any disclosure, copying, distribution or use of the contents of this information is prohibited. If you have received this electronic message in error, please notify us by telephone or e-mail (to the number or address above) immediately. Any views, opinions or advice expressed in this electronic message are not necessarily the views, opinions or advice of PRIMUS. It is the responsibility of the recipient to ensure that any attachments are virus free and PRIMUS bears no responsibility for any loss or damage arising in any way from the use thereof.The term "PRIMUS" includes its affiliates.

---

 Pour la version en français de ce message, veuillez voir
http://www.primustel.ca/fr/legal/cs.htm

**Comment by mihall-primus** [comment]
Hi Savasamy,

Double ah ha!

It seems timestamp is maybe a reserved word?  COMMONAPACHELOG stores the timestamp in a field called, logically enough, timestamp.  However, Graylog doesn't seem to like that.  If I change the field name to ts, it works!

Thanks for pointing me in the right direction,

Michael

On Wed, 2016-04-27 at 11:44 -0400, Michael Hall wrote:
Hi Savasamy,

Ah ha!

2016-04-27_15:21:09.13131 [344]: index [graylog_73], type [message], id [aa4ba352-0c8b-11e6-afd3-005056a47198], message [MapperParsingException[failed to parse [timestamp]]; nested: MapperParsingException[failed to parse date field [27/Apr/2016:11:21:05 -0400], tried both date format [yyyy-MM-dd HH:mm:ss.SSS], and timestamp number with locale []]; nested: IllegalArgumentException[Invalid format: "27/Apr/2016:11:21:05 -0400" is malformed at "/Apr/2016:11:21:05 -0400"]; ]

I changed my extractor to just %{IP}, instead of %{COMMONAPACHELOG}, and it works fine.  So it looks like the problem is with the Grok pattern.  The weird part is, when I test the pattern on the Extractor Configuration page, it successfully parses the timestamp.  But then when it's actually running the extractor, it fails.

Michael

On Tue, 2016-04-26 at 17:38 -0700, Sivasamy Kaliappan wrote:
Hi Michael,

Are there any exceptions present in graylog server log files?

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHubhttps://github.com/sivasamyk/graylog-beats-plugin/issues/4#issuecomment-214929967

---

 This electronic message contains information from Primus Management ULC ("PRIMUS") , which may be legally privileged and confidential. The information is intended to be for the use of the individual(s) or entity named above. If you are not the intended recipient, be aware that any disclosure, copying, distribution or use of the contents of this information is prohibited. If you have received this electronic message in error, please notify us by telephone or e-mail (to the number or address above) immediately. Any views, opinions or advice expressed in this electronic message are not necessarily the views, opinions or advice of PRIMUS. It is the responsibility of the recipient to ensure that any attachments are virus free and PRIMUS bears no responsibility for any loss or damage arising in any way from the use thereof.The term "PRIMUS" includes its affiliates.

---

 Pour la version en français de ce message, veuillez voir
http://www.primustel.ca/fr/legal/cs.htm
