### ISSUE TITLE
Support for the recent released Graylog version 2.0

### ISSUE THREAD

**Issue by danlsgiga** [sivasamyk/graylog-beats-plugin#5]
Just wondering if this plugin was tested on the new Graylog version 2.
Thanks

**Comment by joschi** [comment]
There's another Beats plugin working with Graylog 2.0.0 and higher (but not with Graylog 1.x): https://marketplace.graylog.org/addons/22014b12-9358-4056-9402-d3eb69f9560e

(Disclaimer: I wrote that plugin and it's officially maintained by Graylog now)

**Comment by danlsgiga** [comment]
Wow, that is awesome news! Thanks @joschi!!
